// src/config/worlds.config.js
// 10 Topic-Themed Worlds for NthQuest (Grade 7 · Simple Nth Term)
// Strictly follows NthQuest_Grade7_PRD.md §9 and NthQuest_Grade7_TRD.md §4.1

export const WORLDS = [
  {
    id: 0,
    name: "Which Stall Is This?",
    emoji: "🚶",
    accent: "var(--world-0)",
    description: "n as position; read a position–term table both ways",
    conceptFocus: "position-and-term",
    boss: { name: "The Confused Queue", emoji: "🚶", reward: "Position Badge" },
  },
  {
    id: 1,
    name: "Read the Signboard",
    emoji: "🪧",
    accent: "var(--world-1)",
    description: "Substitute into an and n + b",
    conceptFocus: "substitute-simple",
    boss: { name: "The Smudged Signboard", emoji: "🪧", reward: "Reader's Badge" },
  },
  {
    id: 2,
    name: "Two-Part Signboards",
    emoji: "➕",
    accent: "var(--world-2)",
    description: "Substitute into an + b and an − b",
    conceptFocus: "substitute-two-part",
    boss: { name: "The Two-Part Trickster", emoji: "➕", reward: "Substitution Badge" },
  },
  {
    id: 3,
    name: "Far Down the Street",
    emoji: "🛣️",
    accent: "var(--world-3)",
    description: "Find far terms (stall 50, 100) from a given nth term",
    conceptFocus: "evaluate-large-n",
    boss: { name: "The Endless Street", emoji: "🛣️", reward: "Long-Range Badge" },
  },
  {
    id: 4,
    name: "Match the Signboard",
    emoji: "🎭",
    accent: "var(--world-4)",
    description: "Choose the right nth term by testing several positions",
    conceptFocus: "match-sequence-to-nth-term",
    boss: { name: "The Mix-Up Merchant", emoji: "🎭", reward: "Matcher's Badge" },
  },
  {
    id: 5,
    name: "The Times-Table Trick",
    emoji: "🐯",
    accent: "var(--world-5)",
    description: "Nth term of pure-multiples sequences (an)",
    conceptFocus: "nth-term-of-multiples",
    boss: { name: "The Times-Table Tiger", emoji: "🐯", reward: "Multiples Badge" },
  },
  {
    id: 6,
    name: "Off by a Little",
    emoji: "🦝",
    accent: "var(--world-6)",
    description: "Build an ± b by comparing with the times table",
    conceptFocus: "nth-term-times-table-offset",
    boss: { name: "The Off-By-One Bandit", emoji: "🦝", reward: "Offset Badge" },
  },
  {
    id: 7,
    name: "Price Signboards",
    emoji: "💰",
    accent: "var(--world-7)",
    description: "Write a simple nth term from a price-plus-fee context",
    conceptFocus: "context-to-nth-term",
    boss: { name: "The Haggling Hawker", emoji: "💰", reward: "Price Badge" },
  },
  {
    id: 8,
    name: "Spot the Wrong Signboard",
    emoji: "✏️",
    accent: "var(--world-8)",
    description: "Verify with several positions; correct a wrong formula",
    conceptFocus: "verify-and-correct-nth-term",
    boss: { name: "The Forger of Signs", emoji: "✏️", reward: "Inspector's Badge" },
  },
  {
    id: 9,
    name: "The Grand Night Market",
    emoji: "🏮",
    accent: "var(--world-9)",
    description: "Mixed review of every concept above",
    conceptFocus: "mixed-review",
    boss: { name: "The Night Market Master", emoji: "🏮", reward: "Market Champion Trophy" },
  },
];
